services:
  events-db:
    image: postgres:17-alpine
    container_name: tf-events-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ticketflow
      POSTGRES_PASSWORD: ticketflow
      POSTGRES_DB: events
    ports:
      - "5435:5432"
    volumes:
      - events-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketflow -d events"]
      interval: 5s
      timeout: 3s
      retries: 5

  booking-db:
    image: postgres:17-alpine
    container_name: tf-booking-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ticketflow
      POSTGRES_PASSWORD: ticketflow
      POSTGRES_DB: booking
    ports:
      - "5434:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketflow -d booking"]
      interval: 5s
      timeout: 3s
      retries: 5

  notification-db:
    image: postgres:17-alpine
    container_name: tf-notification-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ticketflow
      POSTGRES_PASSWORD: ticketflow
      POSTGRES_DB: notification
    ports:
      - "5436:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketflow -d notification"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tf-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: tf-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ticketflow
      RABBITMQ_DEFAULT_PASS: ticketflow
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  events-db-data:
  booking-db-data:
  notification-db-data: